# 新浪开放平台账号信息
sinaopen:
  api_url: https://api.weibo.com/2/short_url/shorten.json
  access_token: 2.00FMIcADLQuzWB8dcef1c8f7HxYv2E


# 二维码参数信息
qrcodeinfo:
  logo_path: /logo/logo.jpg
  logo_width: 90
  logo_height: 90
  qr_code_size: 300
  charset: utf-8
  picture_format: png
  create_path: D://picture/qrCode


# 条形码参数信息
barcodeinfo:
  width: 300
  height: 50
  word_height: 75
  charset: utf-8
  picture_format: png
  create_path: D://picture/barCode



